### ISSUE TITLE
Not compatible with Airthings Wave Plus

### ISSUE THREAD

**Issue by MartyTremblay** [custom-components/sensor.airthings_wave#12]
As per https://community.home-assistant.io/t/air-quality-monitor-radon-meter-airthings-wave-plus/102836/3

**Comment by tkorkalainen** [comment]
Hi @MartyTremblay! Any updates related to this? It would be super handy to get Airthings Wave Plus data visible in Home Assistant.

**Comment by MartyTremblay** [comment]
I haven’t had the time yet. It’s been a busy summer. Perhaps in the next few weeks.

**Comment by corvy** [comment]
Following  (Y) I have the Plus too.

**Comment by jjanderson** [comment]
Hi, 

I was wondering if the plus compatibility will be available soon? I have just ordered one, so when it arrives, I will be happy to assist with testing if required?

THanks for all your hard work on bringing this integration to HA...
