### ISSUE TITLE
Not showing up on the Dashboard

### ISSUE THREAD

**Issue by 1iveowl** [custom-components/sensor.airthings_wave#14]
I find Airthings value in `Developer Tools/States` however nothing is showing up on the `Overview`.

Also I get this error:

> Radon level is : got an exception: could not convert string to float: 'unknown'

**Comment by MartyTremblay** [comment]
The sensor requires that you add the Lovelace card (Entities or Gauge) yourself. See here:
https://www.home-assistant.io/lovelace/
https://www.home-assistant.io/lovelace/gauge/

As for the warning in the log, there's a known issue where values don't display until the first scan interval (defaults to 5 minutes) (see here https://github.com/custom-components/sensor.airthings_wave/issues/2 )

Let me know if this is what you're experiencing.

**Comment by MartyTremblay** [comment]
@1iveowl , please let me know if I should keep this issue open. I'll close it otherwise.
