### ISSUE TITLE
It takes up to (interval_scan) minutes to display values

### ISSUE THREAD

**Issue by MartyTremblay** [custom-components/sensor.airthings_wave#2]
For whatever reason, the component only returns non 'unknown' values after the first interval_scan (5 minutes default) loops through

**Comment by ludeeus** [comment]
Probably missing True as an argument to ads_entities (I have not looked at it)

**Comment by ludeeus** [comment]
Example:
```python
add_entities([AirthingsAccel(name + " Acceleration", mon), True])
```

**Comment by MartyTremblay** [comment]
Thanks @ludeeus . I tried adding the extra True parameter in my environment but I'm seeing the same result. I'll investigate further.

**Comment by ludeeus** [comment]
Aha!
That `True` flag runs `async_update` or `update` methods inside the sensor classes during startup, but you do not have that :/
