### ISSUE TITLE
Airthings Wave Mini

### ISSUE THREAD

**Issue by fenyx13** [custom-components/sensor.airthings_wave#20]
Would it be possible to read an Airthings Wave Mini? The mini only monitors TVOC, temperature and humidity. No radon levels.

**Comment by MartyTremblay** [comment]
Hi @fenyx13 , @sverrham just added support for the Wave Plus. I wonder if the changes made to version 2 (just released) would magically work for the Wave Mini?

**Comment by sverrham** [comment]
Just got this reply from Airtings about support for the wave mini.

> Thank you for reaching out to us at Airthings!
I passed on your query to one of our Product Managers, and unfortunately, this is not documented for the Wave Mini at the moment. However, they expressed there is a plan to do this in the near future.

**Comment by k1rd3rf** [comment]
Just a heads up: https://github.com/Airthings/wavemini-reader :)

**Comment by dingusdk** [comment]
Support for the wave mni could be implemented the same way I just did for the wave 2. 
It looks like the wave mini is also just a subset of the wave plus, but with a different UUID. You can get the UUID in the code from then link above from @k1rd3rf . 
I can do it if you want me to, but I don't have a Wave mini to test, so I think it is better if someone with a wave mini can do this.

**Comment by k1rd3rf** [comment]
I've started creating an integration that pulls from one of the API's. There is unfortunately a requirement to have a Airthings for business account.

https://github.com/k1rd3rf/home-assistant-airthings

**Comment by MartyTremblay** [comment]
> Support for the wave mni could be implemented the same way I just did for the wave 2.
> It looks like the wave mini is also just a subset of the wave plus, but with a different UUID. You can get the UUID in the code from then link above from @k1rd3rf .
> I can do it if you want me to, but I don't have a Wave mini to test, so I think it is better if someone with a wave mini can do this.

@dingusdk , I don't have a mini myself but being that the change is fresh in your mind, could you go ahead and do a PR? The risk is relatively small and I'm sure there are a few folks who would be able to test quickly.

**Comment by dingusdk** [comment]
PR done. Hope it is working without me being able to test it.

**Comment by MartyTremblay** [comment]
I merged the code and released v2.6

For folks that have the mini, please update as soon as possible and provide us feedback in this ticket.

Thanks @dingusdk !

**Comment by MartyTremblay** [comment]
@fenyx13 , If you haven't moved onto something else, would you be able to test this?

**Comment by MartyTremblay** [comment]
Fair to assume that this new integration now works. Closing
