### ISSUE TITLE
Support for Wave 2nd Gen

### ISSUE THREAD

**Issue by sverrham** [custom-components/sensor.airthings_wave#23]
https://github.com/Airthings/wave-reader

They added support for a 2nd Gen device.
Should be simple to update and support.

add this uuid: "b42e4dcc-ade7-11e4-89d3-123b93f75cba"
And add a new decoder and decode as done in their code, it will be similar to the current Wave pluss decoder

**Comment by dajo** [comment]
@sverrham Is there a way to determine which gen you have?

**Comment by sverrham** [comment]
Serial nr 2900xxxxx is gen one, serial 2950xxxxx is gen two.

**Comment by dajo** [comment]
Thanks. OT, but my SN is 29300xxxxx.

**Comment by sverrham** [comment]
From a quick google search that looks like the wave mini, are you sure you
don't have a wave mini?

https://cdn2.hubspot.net/hubfs/4406702/Website/Manuals/Wave-Mini/airthings-wave-mini-manual.pdf

can see in the linked user manual 29300

**Comment by rhgiter** [comment]
I have a airthings wave plus (model 2930) SN:2930xxxxx

how do I add this to my RP3+b 
I have installed HACS and this is in the config 
sensor:
  - platform: airthings_wave
    scan_interval: 120

but iI don't see it in Known_devices or in HA ?

**Comment by MartyTremblay** [comment]
Welcome @rhgiter !

I'm going to state the obvious just because there's very little to go with.

- Have you looked at the logs?
- Devices will be named to something like `sensor.98_07_xx_xx_xx_xx_radon_1day_avg`
- These devices are Bluetooth LE (Low Energy) devices, their practical range between the device and the Pi is about 15 feet (line of sight).

**Comment by rhgiter** [comment]
Thanks   I can see it now ,but all my entities writes available - ?

[image: image.png]
/René


Den tor. 26. mar. 2020 kl. 13.33 skrev Martin Tremblay <
notifications@github.com>:

**Comment by dajo** [comment]
OT still, but @sverrham it looks like both of us have pluses with 2930xxxxx. I kinda gave up for now as I'm definitely further than the practical range and I don't really understand how to use pip with my HA setup.

**Comment by rhgiter** [comment]
i got mine to work.  but the range from PI3b+ to wave is 5 mtr and it wont work ... when its 2,5 t will :-/
