### ISSUE TITLE
HA 0.115 will remove "mdi:periodic-table-co2"

### ISSUE THREAD

**Issue by mindtripper** [custom-components/sensor.airthings_wave#27]
Hi!

Great component!

Changes coming in the next version of HA will require a minor change to the code.
From HA logs: "Icon mdi:periodic-table-co2 was renamed to mdi:molecule-co2, please change your config, it will be removed in version 0.115."

Not proficient in Git or I'd pull and propose change.

**Comment by MartyTremblay** [comment]
Thanks for the heads-up!
