### ISSUE TITLE
Sensor is not created in Home Assistant

### ISSUE THREAD

**Issue by Vendo232** [custom-components/sensor.airthings_wave#32]
Hi

I`m running HA on NUC with Mint Linux and HA in Docker.

In Mint I was able to obtain MAC of the Airthings wave and run env/bin/python3 radonwave.py ADDRESS and it worked in command line.

In HA I get this error

Log Details (ERROR)
Logger: custom_components.airthings_wave.airthings
Source: custom_components/airthings_wave/airthings.py:191
Integration: airthings_wave (documentation)
First occurred: 11:53:52 PM (1 occurrences)
Last logged: 11:53:52 PM

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/airthings.py", line 191, in get_info
    dev = self.adapter.connect(mac, 3)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to 00:81:F9:77:82:D3 after 3 seconds.

reading from command line
![image](https://user-images.githubusercontent.com/44098230/93297976-9804a480-f7af-11ea-8beb-2a2de8b3706c.png)

**Comment by MartyTremblay** [comment]
I've been having the same issue since upgrading to HassOS 4.13 yesterday on my Odroid XU4. I wasn't sure if it was just me...

The logs don't say much except that it cannot connect. I'm suspecting a low-level USB change in the OS is causing this. More testing is required...

Anyone using the built-in Raspberry Pi bluetooth, please confirm whether or not this components works with HassOS 4.13. I'd like to determine if it's strictly a USB or bluetooth issue.

**Comment by Vendo232** [comment]
Thank you Marty, the sensor has not been even created in HA in my case.
The USB BT dongle works OK in linux.

**Comment by HerveB** [comment]
Thanks for creating this integration. I finally got to try it but it is not working for me: sensors are not created in Hass.io. I have tested that my bluetooth USB adaptor is working fine. I have also tried to run the script to detect the devices but it failed with an error message. Could it be a compatibility issue with the version of python bundled with Hass.io? I am using v0.115.6.
Thanks!

**Comment by MartyTremblay** [comment]
Yes indeed. After upgrading Hass.io from v0.114.x, my instance also has stopped working.
Anyone willing to dig a bit to resolve this? I might not be able to get to this for the next few weeks.

**Comment by Vendo232** [comment]
here is a guide how to connect to HA for Wave and Wave 2.

https://community.home-assistant.io/t/airthings-wave-integration-in-ha/229009

**Comment by Vendo232** [comment]
> Thanks for creating this integration. I finally got to try it but it is not working for me: sensors are not created in Hass.io. I have tested that my bluetooth USB adaptor is working fine. I have also tried to run the script to detect the devices but it failed with an error message. Could it be a compatibility issue with the version of python bundled with Hass.io? I am using v0.115.6.
> Thanks!

here is a guide how to connect to HA for Wave and Wave 2.

https://community.home-assistant.io/t/airthings-wave-integration-in-ha/229009

**Comment by Vendo232** [comment]
here is a guide how to connect Wave and Wave 2 to HA.

https://community.home-assistant.io/t/airthings-wave-integration-in-ha/229009
