### ISSUE TITLE
[elevation] is an invalid option for [sensor.airthings_wave].

### ISSUE THREAD

**Issue by Aephir** [custom-components/sensor.airthings_wave#37]
I just installed via HACS, and copied the [example configuration from the repo](https://github.com/custom-components/sensor.airthings_wave#getting-started).

When trying to `Verify configuration` in HA configuration panel, I get the following error:

```
Invalid config for [sensor.airthings_wave]: [elevation] is an invalid option for [sensor.airthings_wave]. Check: sensor.airthings_wave->elevation. (See ?, line ?). 
```

And no sensor appears. If I remove the `elevation` option, they pop up just fine.

**Comment by MartyTremblay** [comment]
While the elevation was merged to master a few weeks ago, it was never released. I just released it in version 2.7.  I should be available in HACS soon.
