### ISSUE TITLE
radon_level text attribute incorrect

### ISSUE THREAD

**Issue by altaic** [custom-components/sensor.airthings_wave#38]
RadonSensor's radon_level attribute assumes the becquerel unit is being used. If the sensor is setup to use picocurie, the textual representation of the sensor is quite incorrect.

**Comment by MartyTremblay** [comment]
You are absolutely correct. Can you submit your changes as a PR to this repository?

**Comment by MartyTremblay** [comment]
Oops, my bad. Just noticed you have already. I'll merge and release a new version.
