### ISSUE TITLE
error after restart  / Failed intial setup.

### ISSUE THREAD

**Issue by marsin-crypto** [custom-components/sensor.airthings_wave#48]
Logger: custom_components.airthings_wave.sensor
Source: custom_components/airthings_wave/airthings.py:233
Integration: airthings_wave (documentation, issues)
First occurred: 7:47:23 PM (1 occurrences)
Last logged: 7:47:23 PM

Failed intial setup.
Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 198, in setup_platform
    sensordata = airthingsdetect.get_sensor_data()
  File "/config/custom_components/airthings_wave/airthings.py", line 233, in get_sensor_data
    char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 508, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected

**Comment by MartyTremblay** [comment]
Thanks for the ticket @marsin-crypto 

Did the component work for you before or is this a first-time install?

I ask since the component was recently updated to use a different bluetooth library and I'm trying to determine if the issue you're describing is caused by the update.

**Comment by sverrham** [comment]
So it looks like we should add some exception handling. 
I can see this is the new code and that it worked, because you got quite far in the process.

looks like a disconnect for some reason after you had a connection, might be releated to something also using the bluetooth on the device or something causing the airthings device to drop the connection, connecting with your phone or hub at the same time maybe?

**Comment by marsin-crypto** [comment]
Yes. Component worked after this morning update. I saw you closed issue(Bluetooth related) I previously commented. And I immediately updated. First HA restart went without problem. AND IT WORKED. I didn't see any Bluetooth related warnings in the log. But then I restarted HA again I got this error. Hence I opened issue. ( hoping it will help to improve component). Now after I opened issue I restarted once again and component loaded. And it seems ok ( no warnings in the HA log). Sorry if I caused confusion.
________________________________
