### ISSUE TITLE
need version key for future HA release

### ISSUE THREAD

**Issue by terwilliker** [custom-components/sensor.airthings_wave#51]
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 8:27:09 AM (1 occurrences)
Last logged: 8:27:09 AM

No 'version' key in the manifest file for custom integration 'airthings_wave'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'airthings_wave'

**Comment by MartyTremblay** [comment]
Thanks for the heads-up however this was resolve as part of #45  and released in v2.9.1
