### ISSUE TITLE
Failed initial setup

### ISSUE THREAD

**Issue by tonintcalls** [custom-components/sensor.airthings_wave#54]
Hi,

I copied the folder to /homeassistant/custom_components/airthings_wave, edited the configurations.yaml as instructed, but got this Error in logs:

Failed intial setup.

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 178, in setup_platform
    num_devices_found = airthingsdetect.find_devices()
  File "/config/custom_components/airthings_wave/airthings.py", line 164, in find_devices
    advertisements = scanner.scan(timeout)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)

Could you tell me whether I have done anything wrong?

Thanks!

**Comment by Afterster** [comment]
If running HomeAssistant Core, be sure you added appropriate permissions to run bluetooth stack to the user running homeassistant.

`sudo apt-get install libcap2-bin
sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which python3))
sudo setcap 'cap_net_raw+ep' $(readlink -f $(which hcitool))`

(from https://www.home-assistant.io/integrations/bluetooth_le_tracker/#rootless-setup)

**Comment by jjanderson** [comment]
Hi,

I am also experiencing this issue.

I was using this fork: https://github.com/gkreitz/homeassistant-airthings for a while, but that repo seems to have been abandoned. This was after trying your component and never being able to get it to work. The repo from gkreitz was working until the last update to HA.

In terms of the logs, when using your component, I get:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:298
Integration: Sensor (documentation, issues)
First occurred: 10:06:55 (1 occurrences)
Last logged: 10:06:55

Setup of platform airthings_wave is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

I am not sure where to go from here to get this working?

Any help would be greatly appreciated.

Many thanks

**Comment by sverrham** [comment]
If this is still an issue reopen, closing it for now.
