### ISSUE TITLE
View Plus support

### ISSUE THREAD

**Issue by clod986** [custom-components/sensor.airthings_wave#56]
I have purchased a View Plus and realized that there's no repository that can port it inside Home Assistant, which is a shame since that's the reason why I chose to pay the extra bucks.

The API seems well documented https://developer.airthings.com/consumer-api-docs/ but this project aims to handle the bluetooth devicese, hence I was wondering if there's any plan to integrate it or if I should consider starting a new repository to do it.

**Comment by sondercoder** [comment]
I also received a View Plus, and if there is anything I can do to assist in adding this to a supported devices, I'll be glad to help.  I am looking into sniffing the bluetooth traffic to see if I can decode it based on the references in the source code here, but it's a little beyond my current knowledge.

**Comment by MartyTremblay** [comment]
Hi @clod986 
Apologies for not responding sooner.
It appears that the View Plus is a WiFi-only device. This HACS Airthings Wave integration was designed for bluetooth devices in mind. 

The API they published seems straight-forward and should be fairly simple for someone de develop a HA component for it. Unfortunately, unless someone else is willing to put the legwork into it, I am not considering to integrate it into this project.
