### ISSUE TITLE
v7.0

### ISSUE THREAD

**Issue by TheRealDoctor** [custom-components/sensor.airthings_wave#67]
Hey since I got upgraded to HA 7.0 your plugin doesn't work.  Do you think you will be resolving the issue?

**Comment by sverrham** [comment]
probably, do you have some log or more info on what is the issue?

**Comment by sverrham** [comment]
Just updated, seems to work for me

**Comment by TheRealDoctor** [comment]
Sorry false alarm, not sure what was happening, tried everything and then poof it started working again.
