### ISSUE TITLE
No need to register

### ISSUE THREAD

**Issue by fredriklj** [custom-components/sensor.airthings_wave#71]
Under the "Issues" section of the README, it says "It may be possible that the Wave must be connected to the official app at least once before you can use this program, so you will probably not get around registering an account with Airthings".

Yesterday I received a new unit from Airthings (wave plus). I can confirm that you do not have to register the unit with them to get readings out of it. I have never used their app or registered an account. So it seems you can get around sharing your personal data with them by using this code.

**Comment by sverrham** [comment]
Thank you, we should update the docs, I guess I will do it next time I do changes... one of these days...
