### ISSUE TITLE
Error starting for first time

### ISSUE THREAD

**Issue by patrickstanley** [custom-components/sensor.airthings_wave#73]
Tried installing the component, but ran into the following error. Running 2021.12.1 inside docker. I am also running Passive BLE monitor integration which work fine, so HA can talk to the bluetooth dongle. Any suggestions?

`This error originated from a custom integration.

Logger: custom_components.airthings_wave.sensor
Source: custom_components/airthings_wave/airthings.py:164 
Integration: airthings_wave (documentation, issues) 
First occurred: 9:37:21 PM (1 occurrences) 
Last logged: 9:37:21 PM

Failed intial setup.
Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 183, in setup_platform
    num_devices_found = airthingsdetect.find_devices()
  File "/config/custom_components/airthings_wave/airthings.py", line 164, in find_devices
    advertisements = scanner.scan(timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)`

**Comment by sverrham** [comment]
Some access rights, see this https://github.com/IanHarvey/bluepy/issues/313#issuecomment-428324639

**Comment by patrickstanley** [comment]
Challenge seems to be that inside the alpine docker container, there is no setcap. 

`$ docker exec -it home-assistant bash
bash-5.1# whoami
root
bash-5.1# setcap 'cap_net_raw,cap_net_admin+eip' bluepy-helper
bash: setcap: command not found
bash-5.1# 
`

**Comment by sverrham** [comment]
You need to up your google fu 😂 
https://command-not-found.com/setcap

**Comment by patrickstanley** [comment]
Thanks. I am embarrassed that I didn't find that sooner with the amount of time I spent searching. I knew it would be simple, but I just wasn't getting it. It all works now so thank you again.

For the record, I did the following from within the docker container:

```
apk add libcap
setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which python3))
setcap 'cap_net_raw+ep' $(readlink -f $(which hcitool))
```
