### ISSUE TITLE
How is this repo different than the home-assistant airthings integration?

### ISSUE THREAD

**Issue by lone-cloud** [custom-components/sensor.airthings_wave#76]
Was just wondering how the functionality provided with this repo is different from https://github.com/home-assistant/core/tree/dev/homeassistant/components/airthings

**Comment by lone-cloud** [comment]
If that's true it would be nice it was added to the README for future reference.

**Comment by MartyTremblay** [comment]
The simplest way to describe the difference is that ours is "cloudless"  or "cloud-free" and follows one of Home Assistant's guiding principles. 

> Home Assistant keeps your data local, no need for a cloud.
> 
> Home Assistant communicates with your devices locally, and will fallback to pulling in data from the cloud if there is no other option. No data is stored in the cloud, and everything is processed locally.


I'll update the README as suggested

**Comment by MartyTremblay** [comment]
Adding a note to README describing that this component is cloudless.
