### ISSUE TITLE
Component does not support UI-based changing units of measure

### ISSUE THREAD

**Issue by strikeir13** [custom-components/sensor.airthings_wave#78]
On HA 2022.4.1, when trying to change the unit of measurement via the UI, it does not succeed:
![image](https://user-images.githubusercontent.com/688283/162479370-236766b9-6135-4c7c-a06e-4e9648f38590.png)
Units are set to degrees C, I try to change it to F, click 'update', and the change is not saved. Is this an issue with HA core or this component?

**Comment by strikeir13** [comment]
Found more info on this - it was suggested on the forums that `native_unit_of_measurement` needs to be added to the sensor to allow for UI-based unit changes: https://developers.home-assistant.io/docs/core/entity/sensor/#properties Unfortunately, I'm not a developer, so making the necessary changes are beyond my capabilities.

**Comment by sverrham** [comment]
Not shure if it will be that simple, but I do not have time to look into it right now, maybe someone else will have a look if not it might be some time before I fix it.

**Comment by strikeir13** [comment]
I looked into it more yesterday and it appears that HA doesn't have unit conversions for radon units. The HA airthings integration just pulls in radon units with a string for Bq/m3: 
```
from .const import DOMAIN

SENSORS: dict[str, SensorEntityDescription] = {
"radonShortTermAvg": SensorEntityDescription(
        key="radonShortTermAvg",
        native_unit_of_measurement="Bq/m³",
        name="Radon",
    ),
```
from: https://github.com/home-assistant/core/blob/dev/homeassistant/components/airthings/sensor.py

The proper fix for my issue is HA adding a conversion from Bq/m3 to pCi/L, which is a much bigger task and far beyond the scope of this issue and component.
