### ISSUE TITLE
Can't change temperature reading units

### ISSUE THREAD

**Issue by bobloadmire** [custom-components/sensor.airthings_wave#79]
At somepoint my temp reading changed to C, when changing it to F it won't save or apply. It used to read in F, not sure what happened.

**Comment by ecoen66** [comment]
Same here

**Comment by sondercoder** [comment]
I also have this issue after applying the Home Assistant 2022.4.x update.  I believe this update feature is the problem:  https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-unit-of-measurement-for-sensors

**Comment by sondercoder** [comment]
I am not well versed in python or the constraints that home assistant adds, but I been trying to get this to work, and I am not sure why HA isn't seeing, or respecting the 'TEMP_CELSIUS' setting on the sensor units.  I keep rolling back to the 2022.3 update, but other things are starting to break.  Is there anything I can do to help, that as someone that is terrible at coding?

**Comment by sondercoder** [comment]
We need to set 'native_unit_of_measurement' for the device for it to work.  https://community.home-assistant.io/t/unit-of-measurement-2022-4/409860/16

**Comment by lymanepp** [comment]
I submitted PR https://github.com/custom-components/sensor.airthings_wave/pull/82 to fix this.

**Comment by sverrham** [comment]
Hi, sorry I have been super busy last couple of months, maybe I have time to get this in in the next couple of weeks, unless @MartyTremblay has time to look at it.

**Comment by MartyTremblay** [comment]
Thanks @lymanepp for the PR.
Looking at it now

**Comment by MartyTremblay** [comment]
Will push a new release momentarily
