### ISSUE TITLE
Setup of sensor platform airthings_wave is taking over 10 seconds

### ISSUE THREAD

**Issue by fvant** [custom-components/sensor.airthings_wave#80]
Since last week, not sure if it is related but after updating to 2022.5.3 and  hass os 8.0,  the sensor does not show data anymore and the logs have several lines about the timings. Before that all was working fine.

Waiting on integrations to complete setup: sensor.airthings_wave
Setup of sensor platform airthings_wave is taking over 10 seconds
Setup of platform airthings_wave is taking longer than 60 seconds. Startup will proceed without waiting any longer.

**Comment by MartyTremblay** [comment]
I hate to ask but can you check your batteries? I ran into this just last month convinced that the update broke the integration.

**Comment by fvant** [comment]
Sure, 86%, the normal app works fine

**Comment by MartyTremblay** [comment]
Thanks for double-checking.

I'm suspecting that this has to do to you using HASS OS 8.0.RC4 as I haven't updated to it yet.

I'll take a look at the change logs to see if there's anything that looks suspicious.

**Comment by MartyTremblay** [comment]
I have just tested with HASS OS 8.0 GA and seems to be working for me still. Granted, I have the first gen Airwave so I'm unable to reproduce your setup.

**Comment by fvant** [comment]
it connected a few times after i went from 8.0rc3 to 8.0 but then the same
messages showed up in the log and i don't see fresh data.

I will move it closer to the hass to eliminate range issues.

**Comment by MartyTremblay** [comment]
Gotcha. I'll close the ticket for now and feel free to open a new one if it persists.

**Comment by fvant** [comment]
It says Warning but does not update; i could live with some delayed
measurements...

Updating airthings_wave sensor took longer than the scheduled update
interval 0:02:00
20:34:50 – (WARNING) Sensor - message first occurred at May 14, 2022,
21:24:48 and shows up 1416 times
